"""Declarative asset contract for the right SharpaWave hand.

This module deliberately does not import Isaac Sim/IsaacLab.  It is the
single, dependency-light source of truth for the SharpaWave asset paths,
canonical joint order, limits, fingertip frames, and the two supplied URDF
variants.  IsaacLab-specific articulation objects can be built by an adapter
without making this module import-time dependent on a simulator installation.

The canonical order in this file is intentional.  USD layers generated by
different conversion passes enumerate joints in different orders (and include
fixed helper joints), so runtime code must resolve indices by name through
``resolve_joint_indices`` instead of relying on traversal order.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence
import math


SHARPAWAVE_SCHEMA_VERSION = "sharpawave.robot_schema.v1"
SHARPAWAVE_ROBOT_NAME = "sharpawave"
SHARPAWAVE_VARIANT_FLOATING = "floating"
SHARPAWAVE_VARIANT_PEG_FIXEDROT = "peg_fixedrot"

_MODULE_DIR = Path(__file__).resolve().parent
SHARPAWAVE_ASSET_ROOT = _MODULE_DIR / "sharpa-wave-description"
SHARPAWAVE_URDF_ROOT = SHARPAWAVE_ASSET_ROOT / "right_sharpa_wave_urdf"
SHARPAWAVE_MESH_ROOT = SHARPAWAVE_URDF_ROOT / "meshes"
SHARPAWAVE_USD_ROOT = SHARPAWAVE_URDF_ROOT / "usd"
SHARPAWAVE_VENDOR_CONFIG_PATH = SHARPAWAVE_USD_ROOT / "config.yaml"
SHARPAWAVE_ASSET_ROOT_RELATIVE = Path(
    "source/isaaclab_assets/isaaclab_assets/robots/sharpa-wave-description"
)
SHARPAWAVE_URDF_ROOT_RELATIVE = SHARPAWAVE_ASSET_ROOT_RELATIVE / "right_sharpa_wave_urdf"


def _public_asset_path(path: Path) -> str:
    """Serialize an asset path without leaking the checkout's absolute root."""

    return path.relative_to(_MODULE_DIR).as_posix()


@dataclass(frozen=True)
class JointSpec:
    """A canonical actuated-joint description.

    ``lower`` and ``upper`` are copied from the URDF in radians for revolute
    joints and metres for prismatic joints.  For continuous joints the bounds
    describe the source representation; consumers must still handle wrapping
    explicitly.
    """

    name: str
    kind: str
    unit: str
    lower: float | None
    upper: float | None
    effort_limit: float | None
    velocity_limit: float | None
    source: str = "urdf"
    continuous: bool = False

    def validate_value(self, value: float) -> None:
        """Raise ``ValueError`` when a scalar is not finite or out of bounds."""

        if not math.isfinite(float(value)):
            raise ValueError(f"{self.name}: action value must be finite")
        if self.lower is not None and float(value) < self.lower:
            raise ValueError(f"{self.name}: value {value} is below {self.lower}")
        if self.upper is not None and float(value) > self.upper:
            raise ValueError(f"{self.name}: value {value} is above {self.upper}")

    def wrap_value(self, value: float) -> float:
        """Return a finite value, wrapping continuous rotations into one turn."""

        numeric = float(value)
        if not math.isfinite(numeric):
            raise ValueError(f"{self.name}: action value must be finite")
        if not self.continuous:
            self.validate_value(numeric)
            return numeric
        return (numeric + math.pi) % (2.0 * math.pi) - math.pi


@dataclass(frozen=True)
class FingertipSpec:
    """Semantic mapping for a finger pose frame and its contact body."""

    role: str
    pose_frame: str
    contact_body: str
    contact_sensor_required: bool = True
    contact_status: str = "asset_declared_runtime_unverified"


@dataclass(frozen=True)
class ActionSchema:
    """Versioned canonical action contract.

    Numeric scaling is intentionally absent until actuator calibration is
    supplied.  The profile names are still explicit so an adapter can reject
    an unsupported policy rather than silently applying another robot's scale.
    """

    schema_id: str
    joint_names: tuple[str, ...]
    units: tuple[str, ...]
    supported_profiles: tuple[str, ...] = ("joint_delta", "joint_target")
    default_profile: str = "joint_delta"
    action_scale: tuple[float, ...] | None = None
    action_offset: tuple[float, ...] | None = None
    scale_status: str = "missing_calibration"
    wrist_joint_names: tuple[str, ...] = ()
    finger_joint_names: tuple[str, ...] = ()

    @property
    def dimension(self) -> int:
        return len(self.joint_names)

    @property
    def action_dim(self) -> int:
        return self.dimension

    @property
    def wrist_action_dim(self) -> int:
        return len(self.wrist_joint_names)

    @property
    def finger_action_dim(self) -> int:
        return len(self.finger_joint_names)

    @property
    def canonical_joint_names(self) -> tuple[str, ...]:
        return self.joint_names

    def validate_profile(self, profile: str) -> None:
        if profile not in self.supported_profiles:
            raise ValueError(
                f"unsupported action profile {profile!r}; "
                f"supported={self.supported_profiles}"
            )
        if self.default_profile not in self.supported_profiles:
            raise ValueError("default action profile is not supported")


@dataclass(frozen=True)
class RuntimeSchemaReport:
    """Name-resolution result returned before an articulation is controlled."""

    valid: bool
    missing: tuple[str, ...] = ()
    duplicate_runtime_names: tuple[str, ...] = ()
    extra_runtime_names: tuple[str, ...] = ()


@dataclass(frozen=True)
class AssetValidationReport:
    """Filesystem-only validation result; no simulator is required."""

    valid: bool
    missing_paths: tuple[str, ...] = ()
    present_paths: tuple[str, ...] = ()
    warnings: tuple[str, ...] = ()


@dataclass(frozen=True)
class SharpaWaveVariantConfig:
    """Complete declarative configuration for one SharpaWave variant."""

    name: str
    schema_id: str
    urdf_path: Path
    usd_path: Path
    contact_layer_paths: tuple[Path, ...]
    base_joint_names: tuple[str, ...]
    finger_joint_names: tuple[str, ...]
    fixed_joint_names: tuple[str, ...]
    joint_specs: tuple[JointSpec, ...]
    fingertip_specs: tuple[FingertipSpec, ...]
    root_link_name: str = "base_root"
    vendor_fix_base: bool = True
    root_semantics_status: str = "runtime_unverified"
    contact_status: str = "asset_layers_present_runtime_unverified"
    actuator_control_mode: str = "position_target"
    actuator_limits_source: str = "urdf"
    actuator_gains_status: str = "missing_calibration"

    def __post_init__(self) -> None:
        expected = self.base_joint_names + self.finger_joint_names
        actual = tuple(spec.name for spec in self.joint_specs)
        if actual != expected:
            raise ValueError(
                f"{self.name}: joint_specs must match canonical action order; "
                f"expected={expected!r}, actual={actual!r}"
            )
        if len(set(actual)) != len(actual):
            raise ValueError(f"{self.name}: duplicate canonical joint name")
        if len(self.fingertip_specs) != 5:
            raise ValueError(f"{self.name}: expected five fingertip mappings")

    @property
    def action_dim(self) -> int:
        return len(self.joint_specs)

    @property
    def wrist_action_dim(self) -> int:
        """Number of variant-specific root/wrist controls."""

        return len(self.base_joint_names)

    @property
    def finger_action_dim(self) -> int:
        return len(self.finger_joint_names)

    @property
    def continuous_joint_names(self) -> tuple[str, ...]:
        return tuple(spec.name for spec in self.joint_specs if spec.continuous)

    @property
    def canonical_joint_names(self) -> tuple[str, ...]:
        return self.base_joint_names + self.finger_joint_names

    # Friendly aliases used by adapters without exposing mutable collections.
    @property
    def joint_names(self) -> tuple[str, ...]:
        return self.canonical_joint_names

    @property
    def hand_joint_names(self) -> tuple[str, ...]:
        return self.finger_joint_names

    @property
    def wrist_joint_names(self) -> tuple[str, ...]:
        return self.base_joint_names

    @property
    def variant(self) -> str:
        return self.name

    @property
    def schema_version(self) -> str:
        return self.schema_id

    @property
    def asset_path(self) -> Path:
        return self.urdf_path

    @property
    def usd_asset_path(self) -> Path:
        return self.usd_path

    @property
    def fingertip_frames(self) -> tuple[str, ...]:
        return tuple(item.pose_frame for item in self.fingertip_specs)

    @property
    def fingertip_links(self) -> tuple[str, ...]:
        return self.fingertip_frames

    @property
    def contact_body_names(self) -> tuple[str, ...]:
        return tuple(item.contact_body for item in self.fingertip_specs)

    @property
    def contact_links(self) -> tuple[str, ...]:
        return self.contact_body_names

    @property
    def action_schema(self) -> ActionSchema:
        return ActionSchema(
            schema_id=self.schema_id,
            joint_names=self.canonical_joint_names,
            units=tuple(spec.unit for spec in self.joint_specs),
            wrist_joint_names=self.base_joint_names,
            finger_joint_names=self.finger_joint_names,
        )

    def resolve_joint_indices(self, runtime_joint_names: Sequence[str]) -> tuple[int, ...]:
        """Map canonical names to runtime indices, rejecting ambiguous schemas."""

        names = tuple(str(name) for name in runtime_joint_names)
        duplicates = tuple(sorted({name for name in names if names.count(name) > 1}))
        if duplicates:
            raise ValueError(f"{self.name}: duplicate runtime joint names: {duplicates}")
        positions = {name: index for index, name in enumerate(names)}
        missing = tuple(name for name in self.canonical_joint_names if name not in positions)
        if missing:
            raise ValueError(f"{self.name}: runtime schema is missing joints: {missing}")
        return tuple(positions[name] for name in self.canonical_joint_names)

    def validate_runtime_joint_names(
        self, runtime_joint_names: Sequence[str]
    ) -> RuntimeSchemaReport:
        names = tuple(str(name) for name in runtime_joint_names)
        duplicates = tuple(sorted({name for name in names if names.count(name) > 1}))
        expected = set(self.canonical_joint_names)
        present = set(names)
        missing = tuple(name for name in self.canonical_joint_names if name not in present)
        extras = tuple(name for name in names if name not in expected)
        return RuntimeSchemaReport(
            valid=not duplicates and not missing,
            missing=missing,
            duplicate_runtime_names=duplicates,
            extra_runtime_names=extras,
        )

    def validate_files(self) -> AssetValidationReport:
        """Check declared files and mesh references without loading USD."""

        required = [self.urdf_path, self.usd_path, SHARPAWAVE_VENDOR_CONFIG_PATH]
        required.extend(self.contact_layer_paths)
        missing = tuple(_public_asset_path(path) for path in required if not path.is_file())
        present = tuple(_public_asset_path(path) for path in required if path.is_file())
        warnings: list[str] = []
        if not SHARPAWAVE_MESH_ROOT.is_dir():
            warnings.append(f"mesh root is absent: {_public_asset_path(SHARPAWAVE_MESH_ROOT)}")
        if self.vendor_fix_base:
            warnings.append("vendor config requests fix_base=true; runtime root semantics require Kit validation")
        warnings.append("contact sensor API and thresholds require runtime validation")
        return AssetValidationReport(
            valid=not missing,
            missing_paths=missing,
            present_paths=present,
            warnings=tuple(warnings),
        )

    def validate_action_shape(self, action: Any) -> tuple[int, ...]:
        """Validate a batch-first action object and return its shape.

        The method intentionally relies only on a ``shape`` attribute, so it
        accepts NumPy, Torch, and Isaac tensors without importing any of them.
        """

        shape = getattr(action, "shape", None)
        if shape is None:
            raise TypeError("action must expose a batch-first shape")
        normalized = tuple(int(value) for value in shape)
        if len(normalized) != 2 or normalized[-1] != self.action_dim:
            raise ValueError(
                f"{self.name}: expected batch-first shape (N, {self.action_dim}), got {normalized}"
            )
        return normalized

    def default_configuration(self) -> Mapping[str, Any]:
        """Return a serializable configuration snapshot for adapters/tools."""

        return {
            "robot": SHARPAWAVE_ROBOT_NAME,
            "variant": self.name,
            "schema_id": self.schema_id,
            "asset_root": "source/isaaclab_assets/isaaclab_assets/robots/sharpa-wave-description",
            "urdf_path": _public_asset_path(self.urdf_path),
            "usd_path": _public_asset_path(self.usd_path),
            "contact_layer_paths": tuple(_public_asset_path(path) for path in self.contact_layer_paths),
            "root_link_name": self.root_link_name,
            "base_joint_names": self.base_joint_names,
            "finger_joint_names": self.finger_joint_names,
            "fixed_joint_names": self.fixed_joint_names,
            "action_dim": self.action_dim,
            "action_profile": self.action_schema.default_profile,
            "action_profiles": self.action_schema.supported_profiles,
            "action_scale_status": self.action_schema.scale_status,
            "action_units": tuple(spec.unit for spec in self.joint_specs),
            "continuous_joint_names": self.continuous_joint_names,
            "joint_limits": tuple(
                {
                    "name": spec.name,
                    "kind": spec.kind,
                    "lower": spec.lower,
                    "upper": spec.upper,
                    "effort_limit": spec.effort_limit,
                    "velocity_limit": spec.velocity_limit,
                    "continuous": spec.continuous,
                }
                for spec in self.joint_specs
            ),
            "vendor_fix_base": self.vendor_fix_base,
            "root_semantics_status": self.root_semantics_status,
            "contact_status": self.contact_status,
            "actuator_control_mode": self.actuator_control_mode,
            "actuator_limits_source": self.actuator_limits_source,
            "actuator_gains_status": self.actuator_gains_status,
            "calibration_status": "missing_calibration",
            "base_pose_mapper_status": "missing_dependency",
            "policy_status": "missing_dependency",
            "contact_sensor_status": self.contact_status,
            "fingertips": tuple(
                {
                    "role": item.role,
                    "pose_frame": item.pose_frame,
                    "contact_body": item.contact_body,
                    "contact_sensor_required": item.contact_sensor_required,
                    "contact_status": item.contact_status,
                }
                for item in self.fingertip_specs
            ),
        }


def _joint(
    name: str,
    kind: str,
    lower: float,
    upper: float,
    effort: float,
    velocity: float,
    *,
    unit: str,
    continuous: bool = False,
) -> JointSpec:
    return JointSpec(
        name=name,
        kind=kind,
        unit=unit,
        lower=lower,
        upper=upper,
        effort_limit=effort,
        velocity_limit=velocity,
        continuous=continuous,
    )


_FLOATING_BASE_JOINTS = (
    "right_x_joint",
    "right_y_joint",
    "right_z_joint",
    "right_roll_joint",
    "right_pitch_joint",
    "right_yaw_joint",
)
_FIXEDROT_BASE_JOINTS = ("right_x_joint", "right_y_joint", "right_z_joint")
_FINGER_JOINTS = (
    "right_thumb_CMC_FE",
    "right_thumb_CMC_AA",
    "right_thumb_MCP_FE",
    "right_thumb_MCP_AA",
    "right_thumb_IP",
    "right_index_MCP_FE",
    "right_index_MCP_AA",
    "right_index_PIP",
    "right_index_DIP",
    "right_middle_MCP_FE",
    "right_middle_MCP_AA",
    "right_middle_PIP",
    "right_middle_DIP",
    "right_ring_MCP_FE",
    "right_ring_MCP_AA",
    "right_ring_PIP",
    "right_ring_DIP",
    "right_pinky_CMC",
    "right_pinky_MCP_FE",
    "right_pinky_MCP_AA",
    "right_pinky_PIP",
    "right_pinky_DIP",
)

_FLOATING_BASE_SPECS = (
    _joint("right_x_joint", "prismatic", -2.0, 2.0, 200.0, 2.0, unit="m"),
    _joint("right_y_joint", "prismatic", -2.0, 2.0, 200.0, 2.0, unit="m"),
    _joint("right_z_joint", "prismatic", -2.0, 2.0, 200.0, 2.0, unit="m"),
    _joint(
        "right_roll_joint",
        "continuous",
        -math.pi,
        math.pi,
        200.0,
        2.0,
        unit="rad",
        continuous=True,
    ),
    _joint(
        "right_pitch_joint",
        "continuous",
        -math.pi,
        math.pi,
        200.0,
        2.0,
        unit="rad",
        continuous=True,
    ),
    _joint(
        "right_yaw_joint",
        "continuous",
        -math.pi,
        math.pi,
        200.0,
        2.0,
        unit="rad",
        continuous=True,
    ),
)
_FIXEDROT_BASE_SPECS = _FLOATING_BASE_SPECS[:3]

_FINGER_SPECS = (
    _joint("right_thumb_CMC_FE", "revolute", -0.1745, 1.9199, 3.3, 11.84076833, unit="rad"),
    _joint("right_thumb_CMC_AA", "revolute", -0.3491, 0.3491, 3.3, 11.84076833, unit="rad"),
    _joint("right_thumb_MCP_FE", "revolute", -0.5236, 1.3963, 1.864, 16.07692878, unit="rad"),
    _joint("right_thumb_MCP_AA", "revolute", -0.3491, 0.3491, 1.864, 16.07692878, unit="rad"),
    _joint("right_thumb_IP", "revolute", 0.0, 1.7453, 0.638, 11.61831603, unit="rad"),
    _joint("right_index_MCP_FE", "revolute", -0.17453293, 1.5708, 1.864, 16.07692878, unit="rad"),
    _joint("right_index_MCP_AA", "revolute", -0.3491, 0.3491, 1.864, 16.07692878, unit="rad"),
    _joint("right_index_PIP", "revolute", 0.0, 1.7453, 0.638, 11.61831603, unit="rad"),
    _joint("right_index_DIP", "revolute", 0.0, 1.3963, 0.189369, 14.66594768, unit="rad"),
    _joint("right_middle_MCP_FE", "revolute", -0.17453293, 1.5708, 1.864, 16.07692878, unit="rad"),
    _joint("right_middle_MCP_AA", "revolute", -0.3491, 0.3491, 1.864, 16.07692878, unit="rad"),
    _joint("right_middle_PIP", "revolute", 0.0, 1.7453, 0.638, 11.61831603, unit="rad"),
    _joint("right_middle_DIP", "revolute", 0.0, 1.3963, 0.189369, 14.66594768, unit="rad"),
    _joint("right_ring_MCP_FE", "revolute", -0.17453293, 1.5708, 1.864, 16.07692878, unit="rad"),
    _joint("right_ring_MCP_AA", "revolute", -0.3491, 0.3491, 1.864, 16.07692878, unit="rad"),
    _joint("right_ring_PIP", "revolute", 0.0, 1.7453, 0.638, 11.61831603, unit="rad"),
    _joint("right_ring_DIP", "revolute", 0.0, 1.3963, 0.189369, 14.66594768, unit="rad"),
    _joint("right_pinky_CMC", "revolute", 0.0, 0.2618, 0.5285, 35.07416159, unit="rad"),
    _joint("right_pinky_MCP_FE", "revolute", -0.17453293, 1.5708, 1.864, 16.07692878, unit="rad"),
    _joint("right_pinky_MCP_AA", "revolute", -0.3491, 0.3491, 1.864, 16.07692878, unit="rad"),
    _joint("right_pinky_PIP", "revolute", 0.0, 1.7453, 0.638, 11.61831603, unit="rad"),
    _joint("right_pinky_DIP", "revolute", 0.0, 1.3963, 0.189369, 14.66594768, unit="rad"),
)

_FINGERTIPS = (
    FingertipSpec("thumb", "right_thumb_fingertip", "right_thumb_elastomer"),
    FingertipSpec("index", "right_index_fingertip", "right_index_elastomer"),
    FingertipSpec("middle", "right_middle_fingertip", "right_middle_elastomer"),
    FingertipSpec("ring", "right_ring_fingertip", "right_ring_elastomer"),
    FingertipSpec("pinky", "right_pinky_fingertip", "right_pinky_elastomer"),
)

_FIXED_JOINTS = (
    "right_thumb_elastomer_fix_joint",
    "right_thumb_fingertip_fix_joint",
    "right_index_elastomer_fix_joint",
    "right_index_fingertip_fix_joint",
    "right_middle_elastomer_fix_joint",
    "right_middle_fingertip_fix_joint",
    "right_ring_elastomer_fix_joint",
    "right_ring_fingertip_fix_joint",
    "right_pinky_elastomer_fix_joint",
    "right_pinky_fingertip_fix_joint",
)


SHARPAWAVE_FLOATING_CFG = SharpaWaveVariantConfig(
    name=SHARPAWAVE_VARIANT_FLOATING,
    schema_id=f"{SHARPAWAVE_SCHEMA_VERSION}.{SHARPAWAVE_VARIANT_FLOATING}",
    urdf_path=SHARPAWAVE_URDF_ROOT / "right_sharpa_wave_floating.urdf",
    usd_path=SHARPAWAVE_USD_ROOT / "right_sharpa_wave_floating_runtime_contact_deinstanced.usd",
    contact_layer_paths=(
        SHARPAWAVE_USD_ROOT / "right_sharpa_wave_floating_runtime_contact_deinstanced.usd",
        SHARPAWAVE_USD_ROOT
        / "configuration/right_sharpa_wave_floating_runtime_contact_deinstanced_sensor.usd",
    ),
    base_joint_names=_FLOATING_BASE_JOINTS,
    finger_joint_names=_FINGER_JOINTS,
    fixed_joint_names=_FIXED_JOINTS,
    joint_specs=_FLOATING_BASE_SPECS + _FINGER_SPECS,
    fingertip_specs=_FINGERTIPS,
)

SHARPAWAVE_PEG_FIXEDROT_CFG = SharpaWaveVariantConfig(
    name=SHARPAWAVE_VARIANT_PEG_FIXEDROT,
    schema_id=f"{SHARPAWAVE_SCHEMA_VERSION}.{SHARPAWAVE_VARIANT_PEG_FIXEDROT}",
    urdf_path=SHARPAWAVE_URDF_ROOT / "right_sharpa_wave_floating_peg_fixedrot.urdf",
    usd_path=SHARPAWAVE_USD_ROOT / "right_sharpa_wave_floating_3t_fixedrot.usd",
    contact_layer_paths=(
        SHARPAWAVE_USD_ROOT / "configuration/right_sharpa_wave_floating_3t_fixedrot_sensor.usd",
    ),
    base_joint_names=_FIXEDROT_BASE_JOINTS,
    finger_joint_names=_FINGER_JOINTS,
    fixed_joint_names=("right_wrist_fixed_orientation",) + _FIXED_JOINTS,
    joint_specs=_FIXEDROT_BASE_SPECS + _FINGER_SPECS,
    fingertip_specs=_FINGERTIPS,
    root_semantics_status="fixed_orientation_root_runtime_unverified",
)

SHARPAWAVE_VARIANTS: Mapping[str, SharpaWaveVariantConfig] = {
    SHARPAWAVE_VARIANT_FLOATING: SHARPAWAVE_FLOATING_CFG,
    SHARPAWAVE_VARIANT_PEG_FIXEDROT: SHARPAWAVE_PEG_FIXEDROT_CFG,
}
# Compatibility aliases keep discovery ergonomic without introducing another
# configuration object or a second source of joint metadata.
SharpaWaveConfig = SharpaWaveVariantConfig
SHARPAWAVE_CONFIGS = SHARPAWAVE_VARIANTS


def get_sharpawave_variant(name: str = SHARPAWAVE_VARIANT_FLOATING) -> SharpaWaveVariantConfig:
    """Return a configured variant or raise a useful error for typos."""

    key = str(name).strip().lower()
    try:
        return SHARPAWAVE_VARIANTS[key]
    except KeyError as exc:
        choices = ", ".join(sorted(SHARPAWAVE_VARIANTS))
        raise ValueError(f"unknown SharpaWave variant {name!r}; choose one of: {choices}") from exc


def validate_sharpawave_assets() -> Mapping[str, AssetValidationReport]:
    """Validate both declared variants using only repository filesystem state."""

    return {name: config.validate_files() for name, config in SHARPAWAVE_VARIANTS.items()}


__all__ = [
    "ActionSchema",
    "AssetValidationReport",
    "FingertipSpec",
    "JointSpec",
    "RuntimeSchemaReport",
    "SharpaWaveVariantConfig",
    "SharpaWaveConfig",
    "SHARPAWAVE_ASSET_ROOT",
    "SHARPAWAVE_ASSET_ROOT_RELATIVE",
    "SHARPAWAVE_FLOATING_CFG",
    "SHARPAWAVE_MESH_ROOT",
    "SHARPAWAVE_PEG_FIXEDROT_CFG",
    "SHARPAWAVE_ROBOT_NAME",
    "SHARPAWAVE_SCHEMA_VERSION",
    "SHARPAWAVE_URDF_ROOT",
    "SHARPAWAVE_URDF_ROOT_RELATIVE",
    "SHARPAWAVE_USD_ROOT",
    "SHARPAWAVE_VENDOR_CONFIG_PATH",
    "SHARPAWAVE_VARIANTS",
    "SHARPAWAVE_CONFIGS",
    "SHARPAWAVE_VARIANT_FLOATING",
    "SHARPAWAVE_VARIANT_PEG_FIXEDROT",
    "get_sharpawave_variant",
    "validate_sharpawave_assets",
]
